steps:
- name: 'gcr.io/$PROJECT_ID/envsubst'
  args:
  - 'app.yaml'
  env:
  - '_CLIENT_ID=${_CLIENT_ID}'
  - '_CLIENT_SECRET=${_CLIENT_SECRET}'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'app'
  - 'deploy'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
